# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="aibox"
# Bat indexes custom TextMate themes into its cache. Rebuild only when the
# generated aibox theme is not present (normally once after apply/theme switch).
if command -v bat >/dev/null 2>&1 && ! bat --list-themes 2>/dev/null | grep -qx 'aibox'; then
    bat cache --build >/dev/null 2>&1 || true
fi
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#476061,bg:#2D353B,fg:#D3C6AA,fg+:#FFFFFF:bold,hl:#7FBBB3,hl+:#7FBBB3:bold,pointer:#7FBBB3,marker:#A7C080,spinner:#7FBBB3,info:#949F97,header:#949F97,border:#949F97,prompt:#7FBBB3:bold,query:#D3C6AA,disabled:#949F97:dim,gutter:#2D353B,preview-bg:#2D353B,preview-fg:#D3C6AA,separator:#949F97,label:#7FBBB3"
export EZA_COLORS="di=38;2;127;187;179;1:ex=38;2;167;192;128:ln=38;2;131;192;146:fi=0:or=38;2;230;126;128;1:mi=38;2;230;126;128;1:da=38;2;148;159;151;2:sn=38;2;127;187;179:sb=38;2;127;187;179:uu=38;2;148;159;151:un=38;2;148;159;151:gu=38;2;148;159;151:gn=38;2;148;159;151:ga=38;2;167;192;128;1:gm=38;2;219;188;127;1:gd=38;2;230;126;128;1:gv=38;2;219;188;127:gt=38;2;230;152;117;3:xx=38;2;148;159;151;2:da=38;2;148;159;151;2"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;127;187;179;1m'    # section headers, command names
export LESS_TERMCAP_us=$'\e[38;2;219;188;127;4m'    # options, args
export LESS_TERMCAP_so=$'\e[38;2;127;187;179;7m'  # search / status line
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;230;126;128'
