#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#2D353B"

    # Status bar
    [statusbar-bg]="#313244"
    [statusbar-fg]="#D3C6AA"

    # Session (status-left)
    [session-bg]="#7FBBB3"
    [session-fg]="#2D353B"
    [session-prefix-bg]="#E67E80"
    [session-copy-bg]="#83C092"
    [session-search-bg]="#DBBC7F"
    [session-command-bg]="#BC9694"

    # Windows
    [window-active-base]="#7FBBB3"
    [window-active-style]="bold"
    [window-inactive-base]="#7A8478"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#83C092"

    # Panes
    [pane-border-active]="#7FBBB3"
    [pane-border-inactive]="#7A8478"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#7B978C"
    [good-base]="#A7C080"
    [info-base]="#83C092"
    [warning-base]="#DBBC7F"
    [error-base]="#E67E80"
    [disabled-base]="#7A8478"

    # Messages
    [message-bg]="#313244"
    [message-fg]="#D3C6AA"

    # Popup & menu
    [popup-bg]="#313244"
    [popup-fg]="#D3C6AA"
    [popup-border]="#7FBBB3"
    [menu-bg]="#313244"
    [menu-fg]="#D3C6AA"
    [menu-selected-bg]="#7FBBB3"
    [menu-selected-fg]="#2D353B"
    [menu-border]="#7FBBB3"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#D699B6"
    [magenta]="#BC9694"
    [surface]="#313244"
)
