#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#2D353B"

    # Status bar
    [statusbar-bg]="#3C4245"
    [statusbar-fg]="#D3C6AA"

    # Session (status-left)
    [session-bg]="#7FBBB3"
    [session-fg]="#000000"
    [session-prefix-bg]="#E67E80"
    [session-copy-bg]="#83C092"
    [session-search-bg]="#DBBC7F"
    [session-command-bg]="#D699B6"

    # Windows
    [window-active-base]="#7FBBB3"
    [window-active-style]="bold"
    [window-inactive-base]="#949F97"
    [window-inactive-style]="dim"
    [window-activity-style]="dim"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#83C092"

    # Panes
    [pane-border-active]="#7FBBB3"
    [pane-border-inactive]="#949F97"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#8CA8A0"
    [good-base]="#A7C080"
    [info-base]="#83C092"
    [warning-base]="#DBBC7F"
    [error-base]="#E67E80"
    [disabled-base]="#949F97"

    # Messages
    [message-bg]="#3C4245"
    [message-fg]="#D3C6AA"

    # Popup & menu
    [popup-bg]="#3C4245"
    [popup-fg]="#D3C6AA"
    [popup-border]="#7FBBB3"
    [menu-bg]="#3C4245"
    [menu-fg]="#D3C6AA"
    [menu-selected-bg]="#7FBBB3"
    [menu-selected-fg]="#000000"
    [menu-border]="#7FBBB3"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#E69875"
    [magenta]="#D699B6"
    [surface]="#3C4245"
)
