" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#D3C6AA     guibg=#2D353B     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#D3C6AA     guibg=#2D353B
hi Cursor         guifg=#000000 guibg=#7FBBB3
hi lCursor        guifg=#000000 guibg=#7FBBB3
hi LineNr         guifg=#949F97  guibg=#2D353B
hi CursorLineNr   guifg=#7FBBB3 guibg=#3C4245 gui=bold
hi CursorLine     guibg=#3C4245
hi CursorColumn   guibg=#3C4245
hi ColorColumn    guibg=#3C4245
hi VertSplit      guifg=#949F97  guibg=#2D353B
hi WinSeparator   guifg=#949F97  guibg=#2D353B
hi StatusLine     guifg=#000000 guibg=#7FBBB3 gui=bold
hi StatusLineNC   guifg=#949F97  guibg=#3C4245 gui=dim
hi TabLine        guifg=#949F97  guibg=#3C4245 gui=dim
hi TabLineFill    guibg=#2D353B
hi TabLineSel     guifg=#000000 guibg=#7FBBB3 gui=bold
hi SignColumn     guifg=#949F97  guibg=#2D353B
hi FoldColumn     guifg=#949F97  guibg=#2D353B
hi Folded         guifg=#949F97  guibg=#3C4245
hi NonText        guifg=#949F97
hi EndOfBuffer    guifg=#2D353B     guibg=#2D353B
hi SpecialKey     guifg=#949F97
hi MatchParen     guifg=#7FBBB3 guibg=#3C4245 gui=bold
hi Conceal        guifg=#949F97  guibg=#2D353B
hi Directory      guifg=#7FBBB3 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guifg=#FFFFFF guibg=#476061
hi VisualNOS      guifg=#FFFFFF guibg=#476061
hi Search         guifg=#2D353B     guibg=#DBBC7F gui=bold
hi IncSearch      guifg=#2D353B     guibg=#E69875 gui=bold
hi CurSearch      guifg=#000000 guibg=#7FBBB3 gui=bold
hi QuickFixLine   guibg=#3C4245 gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#D3C6AA     guibg=#3C4245
hi PmenuSel       guifg=#000000 guibg=#7FBBB3 gui=bold
hi PmenuSbar      guibg=#3C4245
hi PmenuThumb     guibg=#949F97
hi WildMenu       guifg=#000000 guibg=#7FBBB3 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#E67E80    gui=bold
hi WarningMsg     guifg=#DBBC7F gui=bold
hi ModeMsg        guifg=#7FBBB3 gui=bold
hi MoreMsg        guifg=#A7C080
hi Question       guifg=#7FBBB3
hi Title          guifg=#7FBBB3 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#949F97    gui=italic
hi Constant       guifg=#E69875
hi String         guifg=#A7C080     gui=NONE
hi Character      guifg=#A7C080     gui=NONE
hi Number         guifg=#E69875    gui=NONE
hi Boolean        guifg=#E69875    gui=NONE
hi Float          guifg=#E69875    gui=NONE
hi Identifier     guifg=#D3C6AA
hi Function       guifg=#7FBBB3    gui=NONE
hi Statement      guifg=#D699B6  gui=bold
hi Conditional    guifg=#D699B6  gui=bold
hi Repeat         guifg=#D699B6  gui=bold
hi Label          guifg=#DBBC7F
hi Operator       guifg=#83C092      gui=NONE
hi Keyword        guifg=#D699B6  gui=bold
hi Exception      guifg=#D699B6  gui=bold
hi PreProc        guifg=#D699B6
hi Include        guifg=#D699B6
hi Define         guifg=#D699B6
hi Macro          guifg=#7FBBB3   gui=italic
hi PreCondit      guifg=#DBBC7F
hi Type           guifg=#DBBC7F   gui=bold
hi StorageClass   guifg=#DBBC7F   gui=bold
hi Structure      guifg=#DBBC7F   gui=bold
hi Typedef        guifg=#DBBC7F   gui=bold
hi Special        guifg=#83C092
hi SpecialChar    guifg=#E69875
hi Tag            guifg=#7FBBB3
hi Delimiter      guifg=#D3C6AA
hi SpecialComment guifg=#949F97    gui=italic
hi Debug          guifg=#E69875
hi Underlined     guifg=#7FBBB3   gui=underline
hi Ignore         guifg=#949F97
hi Error          guifg=#E67E80      gui=bold
hi Todo           guifg=#DBBC7F   guibg=#3C4245 gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#A7C080    guibg=#48544A
hi DiffChange     guifg=#DBBC7F   guibg=#53534A
hi DiffDelete     guifg=#E67E80      guibg=#56454A
hi DiffText       guifg=#7FBBB3   guibg=#53534A gui=bold
hi diffAdded      guifg=#A7C080
hi diffRemoved    guifg=#E67E80
hi diffChanged    guifg=#DBBC7F
hi diffFile       guifg=#7FBBB3   gui=bold
hi diffNewFile    guifg=#A7C080    gui=bold
hi diffOldFile    guifg=#E67E80      gui=bold
hi diffLine       guifg=#949F97

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#E67E80
hi SpellCap       gui=undercurl guisp=#DBBC7F
hi SpellLocal     gui=undercurl guisp=#83C092
hi SpellRare      gui=undercurl guisp=#D699B6

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#A7C080    guibg=#2D353B
hi GitGutterChange       guifg=#DBBC7F   guibg=#2D353B
hi GitGutterDelete       guifg=#E67E80      guibg=#2D353B
hi GitGutterChangeDelete guifg=#E69875   guibg=#2D353B
hi SignifySignAdd        guifg=#A7C080    guibg=#2D353B
hi SignifySignChange     guifg=#DBBC7F   guibg=#2D353B
hi SignifySignDelete     guifg=#E67E80      guibg=#2D353B

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#83C092  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#949F97    guibg=#2D353B
hi NormalFloat    guifg=#D3C6AA       guibg=#3C4245
