# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="Coldark-Dark"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#313244,bg:#2D353B,fg:#D3C6AA,fg+:#D3C6AA,hl:#7FBBB3,hl+:#7FBBB3,pointer:#7FBBB3,marker:#A7C080,spinner:#7FBBB3,info:#7A8478,header:#7A8478,border:#7A8478,prompt:#7FBBB3,query:#D3C6AA,disabled:#7A8478,gutter:#2D353B,preview-bg:#2D353B,preview-fg:#D3C6AA,separator:#7A8478,label:#7FBBB3"
export EZA_COLORS="di=38;2;127;187;179;1:ex=38;2;167;192;128:ln=38;2;131;192;146:fi=0:or=38;2;230;126;128:mi=38;2;230;126;128:da=38;2;122;132;120:sn=38;2;127;187;179:sb=38;2;127;187;179:uu=38;2;122;132;120:un=38;2;122;132;120:gu=38;2;122;132;120:gn=38;2;122;132;120:ga=38;2;167;192;128:gm=38;2;219;188;127:gd=38;2;230;126;128:gv=38;2;219;188;127:gt=38;2;214;153;182:xx=38;2;122;132;120:da=38;2;122;132;120"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;127;187;179m'    # bold (section headers, command names)
export LESS_TERMCAP_us=$'\e[38;2;219;188;127m'    # underline (options, args)
export LESS_TERMCAP_so=$'\e[38;2;127;187;179;7m'  # reverse (search / status line)
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;230;126;128'
